# Generated by Django 3.0.3 on 2020-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200303_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(choices=[('T', "Tuner's"), ('S', "Stovall's"), ('C', 'Cedar Lake Cellars'), ('O', 'Other')], default='T', max_length=1),
        ),
    ]
