# Generated by Django 3.0.3 on 2020-03-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200304_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='new_venue',
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
