# Generated by Django 3.0.3 on 2020-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_musician'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(upload_to='static/member_photos'),
        ),
    ]
