# Generated by Django 3.0.3 on 2020-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_category',
            field=models.CharField(choices=[('HS', 'Home page slideshow'), ('GY', 'Photo gallery')], default='GY', max_length=2),
        ),
    ]
