# Generated by Django 3.0.3 on 2020-03-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_photo_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='photo description', max_length=100),
        ),
    ]
