# Generated by Django 3.0.3 on 2020-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_remove_photo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['name']},
        ),
    ]
