# Generated by Django 3.0.3 on 2020-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0020_auto_20200325_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_category',
            field=models.CharField(choices=[('HB', 'Home page photo'), ('GY', 'Photo gallery')], default='GY', max_length=2),
        ),
    ]
