# Generated by Django 3.0.3 on 2020-03-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(choices=[('T', "Tuner's"), ('S', "Stovall's"), ('C', 'Cedar Lake Cellars')], default='T', max_length=1),
        ),
    ]
