# Generated by Django 3.0.3 on 2020-03-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20200304_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-show_date']},
        ),
        migrations.AddField(
            model_name='show',
            name='new_venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(choices=[('T', "Tuner's"), ('S', "Stovall's"), ('C', 'Cedar Lake Cellars'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
