# Generated by Django 3.0.3 on 2020-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20200304_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(choices=[('Tuner\\s', "Tuner's"), ('Stovall\\s Grove', "Stovall's"), ('Cedar Lake Cellars', 'Cedar Lake Cellars'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
