# Generated by Django 3.0.3 on 2020-03-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
