# Generated by Django 3.0.3 on 2020-03-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
