# Generated by Django 3.0.3 on 2020-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0023_hometext_onlinevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='text',
            field=models.TextField(),
        ),
    ]
